name: â€œğŸ”” coucou discord !!!â€

on:
  release:
    types: [published]

jobs:
  send-simple-message:
    runs-on: ubuntu-latest

    steps:
      - name: â€œCoucou discord !!!â€
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          RELEASE_URL="${{ github.event.release.html_url }}"
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"ğŸ“¦ Nouvelle release publiÃ©e : \`${TAG_NAME}\`. Voir : ${RELEASE_URL}\"}" \
               "$WEBHOOK_URL"
